name: http_utils
version: 1.3.2
author: Mike Mitterer  <office@mikemitterer.at>
description: Provides some HTTP related classes portet from Apache HTTP client lib
homepage: https://github.com/MikeMitterer/dart-http_utils

dev_dependencies:
  browser: any
  unittest: any
  validate: any
  intl: any
